[target.x86_64-pc-windows-msvc]
linker = "C:\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\link.exe"

[target.wasm32-unknown-unknown]
# WASM uses its own linker (wasm-ld), no override needed
